USE D2Store

CREATE TABLE dbo.Customers (
    CustomerId UNIQUEIDENTIFIER NOT NULL,
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    Email NVARCHAR(255) NOT NULL,
    PhoneNumber NVARCHAR(20) NULL,
    Address NVARCHAR(255) NULL,
    CreatedDate DATETIME NOT NULL,
    LastModified DATETIME NOT NULL,
    CONSTRAINT PK_Customers PRIMARY KEY CLUSTERED (CustomerId ASC),
    CONSTRAINT UQ_Customers_Email UNIQUE NONCLUSTERED (Email ASC)
);