USE D2Store

CREATE TABLE dbo.Orders (
    OrderId UNIQUEIDENTIFIER NOT NULL,
    CustomerId UNIQUEIDENTIFIER NOT NULL,
    OrderDate DATETIME NOT NULL,
    TotalAmount DECIMAL(18, 2) NOT NULL,
    Status NVARCHAR(20) NOT NULL,
    LastModified DATETIME NOT NULL,
    CONSTRAINT PK_Orders PRIMARY KEY CLUSTERED (OrderId ASC),
    CONSTRAINT FK_Orders_Customers FOREIGN KEY (CustomerId) REFERENCES dbo.Customers(CustomerId)
);