USE D2Store

CREATE TABLE dbo.Products (
    ProductId UNIQUEIDENTIFIER NOT NULL,
    Name NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX) NOT NULL,
    Price DECIMAL(18, 2) NOT NULL,
    StockQuantity INT NOT NULL,
    AddedDate DATETIME NOT NULL,
    LastModified DATETIME NOT NULL,
    CONSTRAINT PK_Products PRIMARY KEY CLUSTERED (ProductId ASC)
);