USE D2Store

CREATE TABLE dbo.Users (
    UserId UNIQUEIDENTIFIER NOT NULL,
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    Email NVARCHAR(255) NOT NULL,
	PasswordHash NVARCHAR(255) NOT NULL,
    PhoneNumber NVARCHAR(20) NULL,
    Address NVARCHAR(255) NULL,
	Role NVARCHAR(20) NOT NULL,
    CreatedDate DATETIME NOT NULL,
    LastModified DATETIME NOT NULL,
    CONSTRAINT PK_Users PRIMARY KEY CLUSTERED (UserId ASC),
    CONSTRAINT UQ_Users_Email UNIQUE NONCLUSTERED (Email ASC)
);